version: "3"

services:
  traefik:
    image: traefik:latest
    command: 
      - "--api.insecure=true" 
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
#      - hello-world
    deploy:
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
    
networks:
  traefik:
    driver: overlay
    external: true
#  hello-world:
#    driver: overlay
#    external: true